export const Categories = [
    "Men's Fashion",
    "Phones & Accessories",
    "Electronic equipment",
    "PC & Laptop",
    "Cameras and Camcorders",
    "Watch",
    "Men's shoes",
    "Household electrical appliances",
    "Sports and Travel",
    "Cars & Motorcycles & Bicycles",
    "Women's Fashion",
    "Mother and Baby",
    "Home & Life",
    "Beauty",
    "Health",
    "Women's shoes",
    "Women's bags and wallets",
    "Women's accessories and jewelry",
    "Online Grocery",
    "Online Bookstore",
];